import type { Metadata } from "next";
import { Press_Start_2P } from "next/font/google";
import "./globals.css";
import "nes.css/css/nes.min.css";
import { Footer, Header } from "@/components/ui";
import { loadResumeData } from "@/lib/loadData";

const pressStart2P = Press_Start_2P({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // load YAML data on the server
  const data = loadResumeData();

  return (
    <html lang="en">
      <body className={pressStart2P.className}>
        <Header github={data.github} linkedin={data.linkedin} />
        {children}
        <Footer projects={data.projects} />
      </body>
    </html>
  );
}
