name: Build and Deploy Resume PDF

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate Markdown from YAML
        run: node scripts/generate_resume.js

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-latex-extra

      - name: Build PDF
        run: pandoc resume.md -o docs/resume.pdf --pdf-engine=xelatex -V mainfont="DejaVu Sans"

      - name: Move PDF to /resumepdf
        run: |
          mkdir -p docs/resumepdf
          mv docs/resume.pdf docs/resumepdf/resume.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
